import pyautogui
import time

time.sleep(3)
pyautogui.keyDown('win')
pyautogui.press('r')
pyautogui.keyUp('win')
time.sleep(2)
pyautogui.write('temp', interval=0.25)
pyautogui.press('enter')
time.sleep(2)
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(3)
pyautogui.press('del')
time.sleep(6)
pyautogui.hotkey('alt', 'f4')

time.sleep(3)
pyautogui.keyDown('win')
pyautogui.press('r')
pyautogui.keyUp('win')
time.sleep(2)
pyautogui.write('%temp%', interval=0.25)
pyautogui.press('enter')
time.sleep(2)
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(3)
pyautogui.press('del')
time.sleep(6)
pyautogui.hotkey('alt', 'f4')

time.sleep(3)
pyautogui.keyDown('win')
pyautogui.press('r')
pyautogui.keyUp('win')
time.sleep(2)
pyautogui.write('prefetch', interval=0.25)
pyautogui.press('enter')
time.sleep(2)
pyautogui.keyDown('ctrl')
pyautogui.press('a')
pyautogui.keyUp('ctrl')
time.sleep(3)
pyautogui.press('del')
time.sleep(6)
pyautogui.hotkey('alt', 'f4')

